[build]
  # 发布目录（当前目录的所有文件）
  publish = "."

# 表单提交成功跳转
[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200

# 表单处理
[[redirects]]
  from = "/"
  to = "/.netlify/functions/submission-created"
  status = 200
  force = true
  conditions = {Resources = ["form"]}

# SPA重定向（放最后）
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
